version: '3'
services:
  auth_postgres:
    image: postgres:9.6
    environment:
      - 'POSTGRES_DB=ripple_auth'
      - 'POSTGRES_PASSWORD=secret'
  auth_redis:
    image: redis
  auth:
    image: ripplefm/auth:0.2.3
    ports:
      - '3001:3000'
    links:
      - auth_postgres
      - auth_redis
    volumes:
      - './support/public_key.pem:/etc/config/public_key.pem'
      - './support/private_key.pem:/etc/config/private_key.pem'
    environment:
      - 'COOKIE_SECRET=secret'
      - 'REDIS_HOST=auth_redis'
      - 'POSTGRES_HOST=auth_postgres'
      - 'POSTGRES_USERNAME=postgres'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_DATABASE=ripple_auth'
      - 'PUBLIC_DOMAIN=http://localhost:3000'
      - 'PUBLIC_KEY_LOCATION=/etc/config/public_key.pem'
      - 'PRIVATE_KEY_LOCATION=/etc/config/private_key.pem'
      - 'MAILGUN_API_KEY= '
      - 'MAILGUN_API_DOMAIN= '
  oauth2-creator:
    image: ripplefm/auth:0.2.3
    command:
      [
        'node',
        'dist/cli',
        'createOAuth2Client',
        'ripple.fm',
        'http://localhost:3000',
        '-t',
      ]
    links:
      - auth_postgres
      - auth_redis
    volumes:
      - './support/public_key.pem:/etc/config/public_key.pem'
      - './support/private_key.pem:/etc/config/private_key.pem'
    environment:
      - 'COOKIE_SECRET=secret'
      - 'REDIS_HOST=auth_redis'
      - 'POSTGRES_HOST=auth_postgres'
      - 'POSTGRES_USERNAME=postgres'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_DATABASE=ripple_auth'
      - 'PUBLIC_DOMAIN=http://localhost:3000'
      - 'PUBLIC_KEY_LOCATION=/etc/config/public_key.pem'
      - 'PRIVATE_KEY_LOCATION=/etc/config/private_key.pem'
      - 'MAILGUN_API_KEY= '
      - 'MAILGUN_API_DOMAIN= '
  api_postgres:
    image: postgres:9.6
    environment:
      - 'POSTGRES_DB=ripple_api'
      - 'POSTGRES_PASSWORD=secret'
  api:
    image: ripplefm/core-api:0.4.1
    command: bash -c "sleep 15; bin/ripple migrate && bin/ripple seed; bin/ripple foreground"
    restart: always
    links:
      - api_postgres
    volumes:
      - './support/public_key.pem:/etc/config/public_key.pem'
      - './support/station_templates.exs:/opt/app/lib/ripple-0.4.1/priv/repo/seeds/station_templates.exs'
    ports:
      - '4000:4000'
    environment:
      - 'PORT=4000'
      - 'REPLACE_OS_VARS=true'
      - 'MIX_ENV=prod'
      - 'MY_POD_IP=127.0.0.1'
      - 'DB_NAME=ripple_api'
      - 'DB_HOSTNAME=api_postgres'
      - 'DB_USERNAME=postgres'
      - 'DB_PASSWORD=secret'
      - 'PUBLIC_KEY_LOCATION=/etc/config/public_key.pem'
      - YOUTUBE_API_KEY
      - SOUNDCLOUD_API_KEY
